---
- name: Subscribe system to RHSM
  hosts: all
  become: true
  tasks:
    - name: Subscribe machine to the Hybrid Cloud Console
      community.general.redhat_subscription:
        state: present
        activationkey: abasso-lab
        org_id: 12560956